#!/bin/bash

mix ecto.create
mkdir -p ~/storage/dev
#iex -S mix phx.server
# last known good
##mix phx.server
export HOST_IP=131.170.250.213
elixir --sname ret --cookie mycookie -S mix phx.server
sleep 10000
